<?php

use Illuminate\Database\Seeder;

class TownshipTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('townships')->delete();

        DB::table('townships')->insert([
            ['state_division_id'=>'1', 'name'=>'Myitkyina'],
            ['state_division_id'=>'1', 'name'=>'Bhamo (Bamaw)'],
            ['state_division_id'=>'1', 'name'=>'Bharma'],
            ['state_division_id'=>'1', 'name'=>'Chipwi (Chibwe)'],
            ['state_division_id'=>'1', 'name'=>'Hpakant (Hpakan, Farkent)'],
            ['state_division_id'=>'1', 'name'=>'Hopin (Hobik)'],
            ['state_division_id'=>'1', 'name'=>'Hsinbo (Sinbo)'],
            ['state_division_id'=>'1', 'name'=>'Hsawlaw (Sawlaw)'],
            ['state_division_id'=>'1', 'name'=>'Injangyang'],
            ['state_division_id'=>'1', 'name'=>'Kamaing (Kamine)',],
            ['state_division_id'=>'1', 'name'=>'Kawnglanghpu (Kaunglanfu)',],
            ['state_division_id'=>'1', 'name'=>'Lweje (Loije, Lwalgyai)',],
            ['state_division_id'=>'1', 'name'=>'Machanbaw',],
            ['state_division_id'=>'1', 'name'=>'Mansi',],
            ['state_division_id'=>'1', 'name'=>'Momauk',],
            ['state_division_id'=>'1', 'name'=>'Moekaung',],
            ['state_division_id'=>'1', 'name'=>'Mohnyin',],
            ['state_division_id'=>'1', 'name'=>'Nogmung (Naungmoon)',],
            ['state_division_id'=>'1', 'name'=>'Pannandin',],
            ['state_division_id'=>'1', 'name'=>'Putao',],
            ['state_division_id'=>'1', 'name'=>'Shwegu',],
            ['state_division_id'=>'1', 'name'=>'Sumprabum',],
            ['state_division_id'=>'1', 'name'=>'Tanai (Tanain)',],
            ['state_division_id'=>'1', 'name'=>'Tsawlaw (Sawlaw)',],
            ['state_division_id'=>'1', 'name'=>'Waingmaw',],
            ['state_division_id'=>'1', 'name'=>'Ywathit',],
            ['state_division_id'=>'2', 'name'=>'Loikaw',],
            ['state_division_id'=>'2', 'name'=>'Demawso',],
            ['state_division_id'=>'2', 'name'=>'Pruhso',],
            ['state_division_id'=>'2', 'name'=>'Shadaw',],
            ['state_division_id'=>'2', 'name'=>'Bawlakhe',],
            ['state_division_id'=>'2', 'name'=>'Hpasawng',],
            ['state_division_id'=>'2', 'name'=>'Maisal',],
            ['state_division_id'=>'3', 'name'=>'Hpa-an',],
            ['state_division_id'=>'3', 'name'=>'Hlaingbwe (Hlinebwe)',],
            ['state_division_id'=>'3', 'name'=>'Papun (Phapun)',],
            ['state_division_id'=>'3', 'name'=>'Thandang',],
            ['state_division_id'=>'3', 'name'=>'Thandanggyi (Thantaunggyi)',],
            ['state_division_id'=>'3', 'name'=>'Myawaddy (Myawadi)',],
            ['state_division_id'=>'3', 'name'=>'Kawkareik (Kawkareit)',],
            ['state_division_id'=>'3', 'name'=>'Kyeikdon',],
            ['state_division_id'=>'3', 'name'=>'Kyain Seikgyi (Kyainseikkyi)',],
            ['state_division_id'=>'3', 'name'=>'Payathonsu (Hpayarthonesu)',],
            ['state_division_id'=>'4', 'name'=>'Tedim',],
            ['state_division_id'=>'4', 'name'=>'Tonzang',],
            ['state_division_id'=>'4', 'name'=>'Falam (Phalam)',],
            ['state_division_id'=>'4', 'name'=>'Hakha (Haka, Harkhar)',],
            ['state_division_id'=>'4', 'name'=>'Thantlang (Htantlang)',],
            ['state_division_id'=>'4', 'name'=>'Kanpetlet (Kanpatlat)',],
            ['state_division_id'=>'4', 'name'=>'Matupi (Matupe)',],
            ['state_division_id'=>'4', 'name'=>'Mindat (Minthet)',],
            ['state_division_id'=>'4', 'name'=>'Paletwa',],
            ['state_division_id'=>'4', 'name'=>'Cikha',],
            ['state_division_id'=>'4', 'name'=>'Rih Khawdar',],
            ['state_division_id'=>'4', 'name'=>'Razua (Yay Zwar)',],
            ['state_division_id'=>'4', 'name'=>'Sami (Samee)',],
            ['state_division_id'=>'10', 'name'=>'Mawlamyaing(Moulmein)',],
            ['state_division_id'=>'10', 'name'=>'Bilin',],
            ['state_division_id'=>'10', 'name'=>'Kyaikmaraw',],
            ['state_division_id'=>'10', 'name'=>'Chaungzon',],
            ['state_division_id'=>'10', 'name'=>'Thanbyuzayat',],
            ['state_division_id'=>'10', 'name'=>'Kyaikkami',],
            ['state_division_id'=>'10', 'name'=>'Mudon',],
            ['state_division_id'=>'10', 'name'=>'Ye',],
            ['state_division_id'=>'10', 'name'=>'Thaton',],
            ['state_division_id'=>'10', 'name'=>'Paung',],
            ['state_division_id'=>'10', 'name'=>'Kyaikto',],
            ['state_division_id'=>'10', 'name'=>'Mottama',],
            ['state_division_id'=>'11', 'name'=>'Sittwe',],
            ['state_division_id'=>'11', 'name'=>'Ann',],
            ['state_division_id'=>'11', 'name'=>'Buthidaung',],
            ['state_division_id'=>'11', 'name'=>'Dalet (Dalat)',],
            ['state_division_id'=>'11', 'name'=>'Gwa',],
            ['state_division_id'=>'11', 'name'=>'Kyaukpyu',],
            ['state_division_id'=>'11', 'name'=>'Kyauktaw',],
            ['state_division_id'=>'11', 'name'=>'Kyeintali',],
            ['state_division_id'=>'11', 'name'=>'Manaung',],
            ['state_division_id'=>'11', 'name'=>'Maungdaw',],
            ['state_division_id'=>'11', 'name'=>'Minbya',],
            ['state_division_id'=>'11', 'name'=>'Mrauk U',],
            ['state_division_id'=>'11', 'name'=>'Myebon',],
            ['state_division_id'=>'11', 'name'=>'Ngapali',],
            ['state_division_id'=>'11', 'name'=>'Pauktaw',],
            ['state_division_id'=>'11', 'name'=>'Ponnagyun',],
            ['state_division_id'=>'11', 'name'=>'Ramree',],
            ['state_division_id'=>'11', 'name'=>'Rathedaung',],
            ['state_division_id'=>'11', 'name'=>'Thandwe',],
            ['state_division_id'=>'11', 'name'=>'Toungup',],
            ['state_division_id'=>'13', 'name'=>'Aungban',],
            ['state_division_id'=>'13', 'name'=>'Toungup',],
            ['state_division_id'=>'13', 'name'=>'Ayetharyar',],
            ['state_division_id'=>'13', 'name'=>'Chinshwehaw',],
            ['state_division_id'=>'13', 'name'=>'Ho-pin',],
            ['state_division_id'=>'13', 'name'=>'Hopang',],
            ['state_division_id'=>'13', 'name'=>'Hopong',],
            ['state_division_id'=>'13', 'name'=>'Hseni',],
            ['state_division_id'=>'13', 'name'=>'Hsi Hseng',],
            ['state_division_id'=>'13', 'name'=>'Hsipaw',],
            ['state_division_id'=>'13', 'name'=>'Kalaw'],
            ['state_division_id'=>'13', 'name'=>'Kengtong'],
            ['state_division_id'=>'13', 'name'=>'Kunhing'],
            ['state_division_id'=>'13', 'name'=>'Kunlong'],
            ['state_division_id'=>'13', 'name'=>'Kutkai'],
            ['state_division_id'=>'13', 'name'=>'Kyaukme'],
            ['state_division_id'=>'13', 'name'=>'Kyethi'],
            ['state_division_id'=>'13', 'name'=>'Lai-Hka'],
            ['state_division_id'=>'13', 'name'=>'Langkho'],
            ['state_division_id'=>'13', 'name'=>'Lashio'],
            ['state_division_id'=>'13', 'name'=>'Lawksawk'],
            ['state_division_id'=>'13', 'name'=>'Loilen'],
            ['state_division_id'=>'13', 'name'=>'Laukkaing'],
            ['state_division_id'=>'13', 'name'=>'Mabein'],
            ['state_division_id'=>'13', 'name'=>'Mantong'],
            ['state_division_id'=>'13', 'name'=>'Mawkmai'],
            ['state_division_id'=>'13', 'name'=>'Mine Hsu'],
            ['state_division_id'=>'13', 'name'=>'Mine Khet'],
            ['state_division_id'=>'13', 'name'=>'Mine Kung'],
            ['state_division_id'=>'13', 'name'=>'Mine Nai'],
            ['state_division_id'=>'13', 'name'=>'Mine Pan'],
            ['state_division_id'=>'13', 'name'=>'Mine Ping'],
            ['state_division_id'=>'13', 'name'=>'Mine Tong'],
            ['state_division_id'=>'13', 'name'=>'Mine Yang'],
            ['state_division_id'=>'13', 'name'=>'Mine Yawng'],
            ['state_division_id'=>'13', 'name'=>'Mine Hsat'],
            ['state_division_id'=>'13', 'name'=>'Mineko'],
            ['state_division_id'=>'13', 'name'=>'Minemit'],
            ['state_division_id'=>'13', 'name'=>'Mineyai'],
            ['state_division_id'=>'13', 'name'=>'Mu Se'],
            ['state_division_id'=>'13', 'name'=>'Namhsan'],
            ['state_division_id'=>'13', 'name'=>'Namtu'],
            ['state_division_id'=>'13', 'name'=>'Nanhkan'],
            ['state_division_id'=>'13', 'name'=>'Nansang'],
            ['state_division_id'=>'13', 'name'=>'Nawnghkio'],
            ['state_division_id'=>'13', 'name'=>'Nyaungshwe'],
            ['state_division_id'=>'13', 'name'=>'Pang Long'],
            ['state_division_id'=>'13', 'name'=>'Pekon'],
            ['state_division_id'=>'13', 'name'=>'Pindaya'],
            ['state_division_id'=>'13', 'name'=>'Pinlaung'],
            ['state_division_id'=>'13', 'name'=>'Tant Yan'],
            ['state_division_id'=>'13', 'name'=>'Taunggyi'],
            ['state_division_id'=>'13', 'name'=>'Techilelk'],
            ['state_division_id'=>'13', 'name'=>'Ywangan'],
            ['state_division_id'=>'5', 'name'=>'Ayadaw'],
            ['state_division_id'=>'5', 'name'=>'Banmauk'],
            ['state_division_id'=>'5', 'name'=>'Budalin'],
            ['state_division_id'=>'5', 'name'=>'Chaung'],
            ['state_division_id'=>'5', 'name'=>'Dabayin'],
            ['state_division_id'=>'5', 'name'=>'Hkamti'],
            ['state_division_id'=>'5', 'name'=>'Homalin'],
            ['state_division_id'=>'5', 'name'=>'Htigyaing'],
            ['state_division_id'=>'5', 'name'=>'Indaw'],
            ['state_division_id'=>'5', 'name'=>'Kalaymyo'],
            ['state_division_id'=>'5', 'name'=>'Kalewa'],
            ['state_division_id'=>'5', 'name'=>'Kanbalu'],
            ['state_division_id'=>'5', 'name'=>'Kani'],
            ['state_division_id'=>'5', 'name'=>'Katha'],
            ['state_division_id'=>'5', 'name'=>'Kawlin'],
            ['state_division_id'=>'5', 'name'=>'Khin U'],
            ['state_division_id'=>'5', 'name'=>'Kyadet'],
            ['state_division_id'=>'5', 'name'=>'Kyunhla'],
            ['state_division_id'=>'5', 'name'=>'Mawlaik'],
            ['state_division_id'=>'5', 'name'=>'Mingun'],
            ['state_division_id'=>'5', 'name'=>'Monywa'],
            ['state_division_id'=>'5', 'name'=>'Myaung'],
            ['state_division_id'=>'5', 'name'=>'Myinmu'],
            ['state_division_id'=>'5', 'name'=>'Pale'],
            ['state_division_id'=>'5', 'name'=>'Paungbyin'],
            ['state_division_id'=>'5', 'name'=>'Pinlebu'],
            ['state_division_id'=>'5', 'name'=>'Sagaing'],
            ['state_division_id'=>'5', 'name'=>'Salingyi'],
            ['state_division_id'=>'5', 'name'=>'Shwebo'],
            ['state_division_id'=>'5', 'name'=>'Tamu'],
            ['state_division_id'=>'5', 'name'=>'Tantsal'],
            ['state_division_id'=>'5', 'name'=>'Wetlet'],
            ['state_division_id'=>'5', 'name'=>'Wuntho'],
            ['state_division_id'=>'5', 'name'=>'Ye-U'],
            ['state_division_id'=>'5', 'name'=>'Yinmabin'],
            ['state_division_id'=>'5', 'name'=>'Mungnii'],
            ['state_division_id'=>'6', 'name'=>'Dawei'],
            ['state_division_id'=>'6', 'name'=>'Launglon'],
            ['state_division_id'=>'6', 'name'=>'Thayetchaung'],
            ['state_division_id'=>'6', 'name'=>'Yebyu'],
            ['state_division_id'=>'6', 'name'=>'Myeik'],
            ['state_division_id'=>'6', 'name'=>'Kyunsu'],
            ['state_division_id'=>'6', 'name'=>'Palaw'],
            ['state_division_id'=>'6', 'name'=>'Taninthayi'],
            ['state_division_id'=>'6', 'name'=>'Kawthoung'],
            ['state_division_id'=>'6', 'name'=>'Bokpyin'],
            ['state_division_id'=>'7', 'name'=>'Bago'],
            ['state_division_id'=>'7', 'name'=>'Thanatpin'],
            ['state_division_id'=>'7', 'name'=>'Kawa'],
            ['state_division_id'=>'7', 'name'=>'Waw'],
            ['state_division_id'=>'7', 'name'=>'Nyaunglebin'],
            ['state_division_id'=>'7', 'name'=>'Madauk'],
            ['state_division_id'=>'7', 'name'=>'Pyuntaza'],
            ['state_division_id'=>'7', 'name'=>'Kyauktaga'],
            ['state_division_id'=>'7', 'name'=>'Pennwegone'],
            ['state_division_id'=>'7', 'name'=>'Daik-U'],
            ['state_division_id'=>'7', 'name'=>'Shwegyin'],
            ['state_division_id'=>'7', 'name'=>'Taungoo'],
            ['state_division_id'=>'7', 'name'=>'Kututmatyi'],
            ['state_division_id'=>'7', 'name'=>'Yaytarshay'],
            ['state_division_id'=>'7', 'name'=>'Kyaukkyi'],
            ['state_division_id'=>'7', 'name'=>'Phyu'],
            ['state_division_id'=>'7', 'name'=>'Oktwin'],
            ['state_division_id'=>'7', 'name'=>'Htantabin'],
            ['state_division_id'=>'7', 'name'=>'Pyay'],
            ['state_division_id'=>'7', 'name'=>'Paukkhaung'],
            ['state_division_id'=>'7', 'name'=>'Padaung'],
            ['state_division_id'=>'7', 'name'=>'Paungde'],
            ['state_division_id'=>'7', 'name'=>'Thegon'],
            ['state_division_id'=>'7', 'name'=>'Shwedaung'],
            ['state_division_id'=>'7', 'name'=>'Thayarwaddy'],
            ['state_division_id'=>'7', 'name'=>'Thonze'],
            ['state_division_id'=>'7', 'name'=>'Letpadan'],
            ['state_division_id'=>'7', 'name'=>'Minhla'],
            ['state_division_id'=>'7', 'name'=>'Okpo'],
            ['state_division_id'=>'7', 'name'=>'Zigon'],
            ['state_division_id'=>'7', 'name'=>'Nattalin'],
            ['state_division_id'=>'7', 'name'=>'Monyo'],
            ['state_division_id'=>'7', 'name'=>'Gyobingauk'],
            ['state_division_id'=>'8', 'name'=>'Magwe'],
            ['state_division_id'=>'8', 'name'=>'Allanmyo (Aunglan, Myaydo)'],
            ['state_division_id'=>'8', 'name'=>'Chauck'],
            ['state_division_id'=>'8', 'name'=>'Gangaw'],
            ['state_division_id'=>'8', 'name'=>'Kamma'],
            ['state_division_id'=>'8', 'name'=>'Minbu'],
            ['state_division_id'=>'8', 'name'=>'Mindon'],
            ['state_division_id'=>'8', 'name'=>'Minhla'],
            ['state_division_id'=>'8', 'name'=>'Myaing'],
            ['state_division_id'=>'8', 'name'=>'Myothit'],
            ['state_division_id'=>'8', 'name'=>'Natmauk'],
            ['state_division_id'=>'8', 'name'=>'Ngape'],
            ['state_division_id'=>'8', 'name'=>'Pakokku'],
            ['state_division_id'=>'8', 'name'=>'Pauk'],
            ['state_division_id'=>'8', 'name'=>'Pwintbyu'],
            ['state_division_id'=>'8', 'name'=>'Sagu'],
            ['state_division_id'=>'8', 'name'=>'Salin'],
            ['state_division_id'=>'8', 'name'=>'Swar'],
            ['state_division_id'=>'8', 'name'=>'Seikphyu'],
            ['state_division_id'=>'8', 'name'=>'Sidoktaya'],
            ['state_division_id'=>'8', 'name'=>'Sinbyugyun'],
            ['state_division_id'=>'8', 'name'=>'Taungdwingyi'],
            ['state_division_id'=>'8', 'name'=>'Thayet'],
            ['state_division_id'=>'8', 'name'=>'Tilin'],
            ['state_division_id'=>'8', 'name'=>'Yenangyaung'],
            ['state_division_id'=>'12', 'name'=>' Ahlon'],
            ['state_division_id'=>'12', 'name'=>' Bahan'],
            ['state_division_id'=>'12', 'name'=>'Botataung'],
            ['state_division_id'=>'12', 'name'=>'Cocokyun'],
            ['state_division_id'=>'12', 'name'=>'Dagon'],
            ['state_division_id'=>'12', 'name'=>'Dagon Myothit(East)'],
            ['state_division_id'=>'12', 'name'=>'Dagon Myothit(North)'],
            ['state_division_id'=>'12', 'name'=>'Dagon Myothit(Seikkan)'],
            ['state_division_id'=>'12', 'name'=>'Dagon Myothit(South)'],
            ['state_division_id'=>'12', 'name'=>'Dala'],
            ['state_division_id'=>'12', 'name'=>'Dawbon'],
            ['state_division_id'=>'12', 'name'=>'Hlaing'],
            ['state_division_id'=>'12', 'name'=>'Hlaingtharya'],
            ['state_division_id'=>'12', 'name'=>'Hlegu'],
            ['state_division_id'=>'12', 'name'=>'Hmawbi'],
            ['state_division_id'=>'12', 'name'=>'Htantabin'],
            ['state_division_id'=>'12', 'name'=>'Insein'],
            ['state_division_id'=>'12', 'name'=>'Kamaryut'],
            ['state_division_id'=>'12', 'name'=>'Kayan'],
            ['state_division_id'=>'12', 'name'=>'Kawhmu'],
            ['state_division_id'=>'12', 'name'=>'Kungyangon'],
            ['state_division_id'=>'12', 'name'=>'Kyauktada'],
            ['state_division_id'=>'12', 'name'=>'Kyauktan'],
            ['state_division_id'=>'12', 'name'=>'Kyeemyindaing'],
            ['state_division_id'=>'12', 'name'=>'Lanmadaw'],
            ['state_division_id'=>'12', 'name'=>'Latha'],
            ['state_division_id'=>'12', 'name'=>'Mayangone'],
            ['state_division_id'=>'12', 'name'=>'Mingaladon'],
            ['state_division_id'=>'12', 'name'=>'Mingalartaungnyunt'],
            ['state_division_id'=>'12', 'name'=>'North Okkalapa'],
            ['state_division_id'=>'12', 'name'=>'Pabedan'],
            ['state_division_id'=>'12', 'name'=>'Pazundaung'],
            ['state_division_id'=>'12', 'name'=>'Sanchaung'],
            ['state_division_id'=>'12', 'name'=>'Seikgyikanaungto'],
            ['state_division_id'=>'12', 'name'=>'Seikkan'],
            ['state_division_id'=>'12', 'name'=>'Shwepyithar'],
            ['state_division_id'=>'12', 'name'=>'South Okkalapa'],
            ['state_division_id'=>'12', 'name'=>'Taikkyi'],
            ['state_division_id'=>'12', 'name'=>'Tamwe'],
            ['state_division_id'=>'12', 'name'=>'Thaketa'],
            ['state_division_id'=>'12', 'name'=>'Thanlyin'],
            ['state_division_id'=>'12', 'name'=>'Thingangkuun'],
            ['state_division_id'=>'12', 'name'=>'Thongwa'],
            ['state_division_id'=>'12', 'name'=>'Twantay'],
            ['state_division_id'=>'12', 'name'=>'Yankin'],
            ['state_division_id'=>'14', 'name'=>'Pathein'],
            ['state_division_id'=>'14', 'name'=>'Kangyidaut'],
            ['state_division_id'=>'14', 'name'=>'Thabaung'],
            ['state_division_id'=>'14', 'name'=>'Ngapudaw'],
            ['state_division_id'=>'14', 'name'=>'Haigyi Island'],
            ['state_division_id'=>'14', 'name'=>'Kyonpyaw'],
            ['state_division_id'=>'14', 'name'=>'Yekyi'],
            ['state_division_id'=>'14', 'name'=>'Kyaunggon'],
            ['state_division_id'=>'14', 'name'=>'Hinthada'],
            ['state_division_id'=>'14', 'name'=>'Zalun'],
            ['state_division_id'=>'14', 'name'=>'Lemyethna'],
            ['state_division_id'=>'14', 'name'=>'Myan Aung'],
            ['state_division_id'=>'14', 'name'=>'Kanaung'],
            ['state_division_id'=>'14', 'name'=>'Kyangin'],
            ['state_division_id'=>'14', 'name'=>'Ingapu'],
            ['state_division_id'=>'14', 'name'=>'Myaungmya'],
            ['state_division_id'=>'14', 'name'=>'Einme'],
            ['state_division_id'=>'14', 'name'=>'Letputta'],
            ['state_division_id'=>'14', 'name'=>'Wakema'],
            ['state_division_id'=>'14', 'name'=>'Mawlamyinegyun'],
            ['state_division_id'=>'14', 'name'=>'Maubin'],
            ['state_division_id'=>'14', 'name'=>'Pantanaw'],
            ['state_division_id'=>'14', 'name'=>'Nyaungdon'],
            ['state_division_id'=>'14', 'name'=>'Danubyu'],
            ['state_division_id'=>'14', 'name'=>'Pyapon'],
            ['state_division_id'=>'14', 'name'=>'Bogale'],
            ['state_division_id'=>'14', 'name'=>'Kyaiklat'],
            ['state_division_id'=>'14', 'name'=>'Dedaye'],
            ['state_division_id'=>'9', 'name'=>'Amarapura'],
            ['state_division_id'=>'9', 'name'=>'Aungmyaythazan'],
            ['state_division_id'=>'9', 'name'=>'Chanayethazan'],
            ['state_division_id'=>'9', 'name'=>'Chanmyathazi'],
            ['state_division_id'=>'9', 'name'=>'Kyaukpadaung'],
            ['state_division_id'=>'9', 'name'=>'Kyaukse'],
            ['state_division_id'=>'9', 'name'=>'Lewe'],
            ['state_division_id'=>'9', 'name'=>'Madaya'],
            ['state_division_id'=>'9', 'name'=>'Mahaaungmyay'],
            ['state_division_id'=>'9', 'name'=>'Mahlaing'],
            ['state_division_id'=>'9', 'name'=>'Meiktila'],
            ['state_division_id'=>'9', 'name'=>'Mogoke'],
            ['state_division_id'=>'9', 'name'=>'Myingyan'],
            ['state_division_id'=>'9', 'name'=>'Myittha'],
            ['state_division_id'=>'9', 'name'=>'Natogyi'],
            ['state_division_id'=>'9', 'name'=>'Ngazun'],
            ['state_division_id'=>'9', 'name'=>'Nyaung-U'],
            ['state_division_id'=>'9', 'name'=>'Patheingyi'],
            ['state_division_id'=>'9', 'name'=>'Pyawbwe'],
            ['state_division_id'=>'9', 'name'=>'Pyigyitagon'],
            ['state_division_id'=>'9', 'name'=>'Pyinoolwin'],
            ['state_division_id'=>'9', 'name'=>'Singu'],
            ['state_division_id'=>'9', 'name'=>'Sintgaing'],
            ['state_division_id'=>'9', 'name'=>'Tada-U'],
            ['state_division_id'=>'9', 'name'=>'Tatkon'],
            ['state_division_id'=>'9', 'name'=>'Taungtha'],
            ['state_division_id'=>'9', 'name'=>'Thabeikkyin'],
            ['state_division_id'=>'9', 'name'=>'Thazi'],
            ['state_division_id'=>'9', 'name'=>'Wundwin'],
            ['state_division_id'=>'9', 'name'=>'Yamethin'],
            ['state_division_id'=>'15', 'name'=>'Pyinmana'],
            ['state_division_id'=>'15', 'name'=>'Tatkon'],
            ['state_division_id'=>'15', 'name'=>'Lewe'],
            ['state_division_id'=>'15', 'name'=>'Ottarathiri'],
            ['state_division_id'=>'15', 'name'=>'Dekkhinathiri'],
            ['state_division_id'=>'15', 'name'=>'Pobbathiri'],
            ['state_division_id'=>'15', 'name'=>'Zabuthiri'],
            ['state_division_id'=>'15', 'name'=>'Zeyathiri'],
            ['state_division_id'=>'9', 'name'=>'Bagan'],
            ['state_division_id'=>'9', 'name'=>'Old Bagan'],
            ['state_division_id'=>'9', 'name'=>'New Bagan'],
        ]);
    }
}
